# 当提交推送到默认分支时，此工作流将构建并推送 Docker 容器到 Azure Web App。

# 此工作流假定您已经创建了目标 Azure App Service Web App。
# 有关说明，请参见 https://docs.microsoft.com/en-us/azure/app-service/quickstart-custom-container?tabs=dotnet&pivots=container-linux

# 要配置此工作流程：

# 1. 下载您的 Azure Web App 的发布配置文件。您可以从 Azure 门户中 Web App 的概述页面下载此文件。
#    更多信息请参见：https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials

# 2. 在您的仓库中创建一个名为 AZURE_WEBAPP_PUBLISH_PROFILE 的秘密，将发布配置文件的内容粘贴为秘密的值。
#    获取发布配置文件的说明请参见：https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret

# 3. 创建一个具有 "repo" 和 "read:packages" 权限的 GitHub 个人访问令牌。

# 4. 在您的 Azure Web App 上创建三个应用设置：
#       DOCKER_REGISTRY_SERVER_URL：将其设置为 "https://ghcr.io"
#       DOCKER_REGISTRY_SERVER_USERNAME：将其设置为拥有仓库的 GitHub 用户名或组织名
#       DOCKER_REGISTRY_SERVER_PASSWORD：将其设置为前一步中个人访问令牌的值

# 5. 更改 AZURE_WEBAPP_NAME 的值。

# 有关 Azure 的 GitHub Actions 更多信息：https://github.com/Azure/Actions
# 有关 Azure Web Apps 部署操作的详细信息：https://github.com/Azure/webapps-deploy
# 有关使用 GitHub Action 工作流开始在 Azure 部署的示例：https://github.com/Azure/actions-workflow-samples

name: 构建并部署容器到 Azure Web App

env:
  AZURE_WEBAPP_NAME: your-app-name  # 将其设置为您的 Azure Web App 名称

on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 配置 Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: 登录到 GitHub 容器仓库
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: 将仓库名称和用户名转换为小写
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: 构建并推送容器镜像到仓库
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 将仓库名称和用户名转换为小写
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: 部署到 Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
