# 此工作流将在更改代码时构建并推送 Web 应用程序到 Azure Static Web App。

# 此工作流假设您已经创建了目标 Azure Static Web App。
# 有关说明，请参见 https://docs.microsoft.com/azure/static-web-apps/get-started-portal?tabs=vanilla-javascript

# 要配置此工作流：
# 1. 在您的仓库中设置一个名为 AZURE_STATIC_WEB_APPS_API_TOKEN 的秘密，其值为您的 Static Web Apps 部署令牌。
#    有关获取部署令牌的说明，请参见：https://docs.microsoft.com/azure/static-web-apps/deployment-token-management
# 2. 更改 APP_LOCATION、API_LOCATION 和 APP_ARTIFACT_LOCATION、AZURE_STATIC_WEB_APPS_API_TOKEN 环境变量的值（下面的部分）。
#    有关设置适当配置值的说明，请转到 https://docs.microsoft.com/azure/static-web-apps/front-end-frameworks

name: 将 Web 应用程序部署到 Azure Static Web Apps

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ $default-branch ]

# 对此工作流中的所有作业和步骤可用的环境变量
env:
  APP_LOCATION: "/" # 客户端代码的位置
  API_LOCATION: "api" # API 源代码的位置 - 可选
  APP_ARTIFACT_LOCATION: "build" # 客户端代码构建输出的位置
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # 包含静态 Web 应用程序部署令牌的秘密

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    permissions:
      contents: read # 用于 actions/checkout 拉取代码
      pull-requests: write # 用于 Azure/static-web-apps-deploy 在 PR 上进行评论
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: 构建并部署作业
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: 构建并部署
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }} # 包含应用程序的 API 令牌的秘密
          repo_token: ${{ secrets.GITHUB_TOKEN }} # 用于 Github 集成（例如 PR 评论）
          action: "upload"
          ###### 仓库/构建配置 - 这些值可以配置以匹配您的应用程序要求。######
          # 有关更多信息，请访问：https://aka.ms/swaworkflowconfig
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
          ###### 仓库/构建配置结束 ######

  close_pull_request_job:
    permissions:
      contents: none
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: 关闭 Pull Request 作业
    steps:
      - name: 关闭 Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }} # 包含应用程序的 API 令牌的秘密
          action: "close"
