# 这个工作流会在将代码提交到默认分支时构建并推送一个Python应用到Azure Web App。

# 这个工作流假定你已经创建了目标Azure App Service Web应用程序。
# 有关说明，请参见https://docs.microsoft.com/zh-cn/azure/app-service/quickstart-python?tabs=bash&pivots=python-framework-flask

# 要配置这个工作流：

# 1. 下载你的Azure Web App的发布配置文件。你可以从Azure门户中Web App的“概述”页面下载此文件。
#    更多信息：https://docs.microsoft.com/zh-cn/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials

# 2. 在你的存储库中创建一个名为AZURE_WEBAPP_PUBLISH_PROFILE的密钥，将发布配置文件的内容粘贴为密钥的值。
#    获取发布配置文件的说明请参见：https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret

# 3. 更改AZURE_WEBAPP_NAME的值。如果需要，下面还可以更改PYTHON_VERSION环境变量的值。

# 有关GitHub Actions for Azure的更多信息：https://github.com/Azure/Actions
# 有关Azure Web Apps Deploy操作的更多信息：https://github.com/Azure/webapps-deploy
# 若要使用GitHub Actions工作流进行Azure部署的更多示例，请访问：https://github.com/Azure/actions-workflow-samples

name: 构建并部署Python应用到Azure Web App

env:
  AZURE_WEBAPP_NAME: 你的应用名称  # 设置为你的Azure Web App的名称
  PYTHON_VERSION: '3.8'              # 设置要使用的Python版本

on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 设置Python版本
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: 创建并启动虚拟环境
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: 安装依赖项
        run: pip install -r requirements.txt

      # 可选：在此添加运行测试的步骤（PyTest、Django测试套件等）

      - name: 为部署任务上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 从构建任务下载构建产物
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .

      - name: '部署到Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}