# 此工作流使用未经 GitHub 认证的操作。
# 这些操作由第三方提供，并受单独的服务条款、隐私政策和支持文档约束。

name: clj-holmes

on:
  push:
    branches: [ $default-branch, $protected-branches ]
  pull_request:
    # 下面的分支必须是上面分支的子集
    branches: [ $default-branch ]
  schedule:
    - cron: $cron-weekly

permissions:
  contents: read

jobs:
  clj-holmes:
    name: 运行 clj-holmes 扫描
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # 仅在私有仓库中由 github/codeql-action/upload-sarif 获取操作运行状态时需要
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 扫描代码
        uses: clj-holmes/clj-holmes-action@200d2d03900917d7eb3c24fc691ab83579a87fcb
        with:
          # rules-repository: 'git://org/private-rules-repo#main'
          output-type: 'sarif'
          output-file: 'clj-holmes-results.sarif'
          fail-on-result: 'false'

      - name: 将分析结果上传到 GitHub 安全选项卡
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{github.workspace}}/clj-holmes-results.sarif
          wait-for-processing: true
