# 该工作流使用GitHub未经认证的操作。
# 这些操作由第三方提供，并受单独的服务条款、隐私政策和支持文档约束。

# 一个示例工作流，检出您的代码并使用 Datree CLI 扫描您想要的 k8s 配置文件，以查找配置错误。
# 然后将结果上传到 GitHub 安全代码扫描。

# 有关更多信息和配置选项，请参阅 https://github.com/datreeio/action-datree/

name: Datree

on:
  push:
    branches: [ $default-branch, $protected-branches ]
  pull_request:
    # 下面的分支必须是上面的分支的子集
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  datree:
    permissions:
      contents: read # 用于 actions/checkout 获取代码
      security-events: write # 用于 github/codeql-action/upload-sarif 上传 SARIF 结果
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 运行 Datree 策略检查
        continue-on-error: true
        uses: datreeio/action-datree@de67ae7a5133d719dc794e1b75682cd4c5f94d8a
        env:
          # 为了使用 Datree 操作，您将需要一个 Datree 令牌。
          # 请参阅 https://hub.datree.io/setup/account-token#1-get-your-account-token-from-the-dashboard 以获取您的令牌。
          DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}
        with:
          # 添加您想要测试的配置文件的路径。
          # 有关所有可用选项，请参阅 https://github.com/datreeio/action-datree#usage。
          path: test-file.yaml
          # 设置 SARIF 输出将生成一个名为 "datree.sarif" 的文件，其中包含您的测试结果
          cliArguments: "-o sarif"
      - name: 将结果上传到 GitHub 安全代码扫描
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: datree.sarif
