# 此工作流使用未经 GitHub 认证的操作。
# 它们由第三方提供，并受单独的服务条款、隐私政策和支持文档约束。

name: DevSkim

on:
  push:
    branches: [ $default-branch, $protected-branches ]
  pull_request:
    branches: [ $default-branch ]
  schedule:
    - cron: $cron-weekly

jobs:
  lint:
    name: DevSkim
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: 检查代码
        uses: actions/checkout@v3

      - name: 运行 DevSkim 扫描器
        uses: microsoft/DevSkim-Action@v1

      - name: 将 DevSkim 扫描结果上传到 GitHub 安全选项卡
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: devskim-results.sarif
