# 此工作流使用未经 GitHub 认证的操作。
# 它们由第三方提供，并受单独的服务条款、隐私政策和支持文档约束。

name: flawfinder

on:
  push:
    branches: [ $default-branch, $protected-branches ]
  pull_request:
    # 以下分支必须是上述分支的子集
    branches: [ $default-branch ]
  schedule:
    - cron: $cron-weekly

jobs:
  flawfinder:
    name: Flawfinder
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: "检出代码"
        uses: actions/checkout@v3

      - name: "flawfinder 扫描"
        uses: david-a-wheeler/flawfinder@8e4a779ad59dbfaee5da586aa9210853b701959c
        with:
          arguments: '--sarif ./'
          output: 'flawfinder_results.sarif'

      - name: "将分析结果上传到 GitHub 安全选项卡"
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{github.workspace}}/flawfinder_results.sarif
