# 此工作流使用未由 GitHub 认证的操作。
# 这些操作由第三方提供，并受独立的服务条款、隐私政策和支持文档约束。

# 此工作流将一组开源静态分析工具集成到 GitHub 代码扫描中。
# 有关文档或提供反馈，请访问 https://github.com/github/ossar-action
name: OSSAR

on:
  push:
    branches: [ $default-branch, $protected-branches ]
  pull_request:
    # 下面的分支必须是上面列出的分支的子集
    branches: [ $default-branch ]
  schedule:
    - cron: $cron-weekly

permissions:
  contents: read

jobs:
  OSSAR-Scan:
    # OSSAR 在 windows-latest 上运行。
    # ubuntu-latest 和 macos-latest 的支持即将推出
    permissions:
      contents: read # 用于 actions/checkout 获取代码
      security-events: write # 用于 github/codeql-action/upload-sarif 上传 SARIF 结果
      actions: read # 仅在私有存储库中由 github/codeql-action/upload-sarif 获取操作运行状态时需要
    runs-on: windows-latest

    steps:
    - name: 检出存储库
      uses: actions/checkout@v3

    # 确保安装了兼容的 dotnet 版本。
    # [Microsoft 安全代码分析 CLI](https://aka.ms/mscadocs) 使用 dotnet v3.1.201 构建。
    # 在运行此操作之前，代理上必须安装大于或等于 v3.1.201 的 dotnet 版本。
    # GitHub 托管的运行程序已经安装了兼容的 dotnet 版本，可以跳过此步骤。
    # 对于自托管运行程序，请确保通过包含以下操作来安装 dotnet 版本 3.1.201 或更高版本：
    # - name: 安装 .NET
    #   uses: actions/setup-dotnet@v2
    #   with:
    #     dotnet-version: '3.1.x'

      # 运行开源静态分析工具
    - name: 运行 OSSAR
      uses: github/ossar-action@v1
      id: ossar

      # 上传结果到安全选项卡
    - name: 上传 OSSAR 结果
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.ossar.outputs.sarifFile }}
