# 此工作流使用 GitHub 未认证的操作。
# 这些操作由第三方提供，并受独立的服务条款、隐私政策和支持文档约束。
# PHPMD 是 PHP Depend 的一个衍生项目，
# 旨在成为著名的 Java 工具 PMD 的 PHP 版本。
# PHPMD 的功能是：它接收给定的 PHP 源代码库
# 并查找该源代码中的几个潜在问题。
# 这些问题可能是：
#   可能的错误
#   子优化代码
#   过于复杂的表达式
#   未使用的参数、方法、属性
# 更多详细信息请访问 https://phpmd.org/

name: PHPMD

on:
  push:
    branches: [ $default-branch, $protected-branches ]
  pull_request:
    # 下面的分支必须是上面列出的分支的子集
    branches: [ $default-branch ]
  schedule:
    - cron: $cron-weekly

permissions:
  contents: read

jobs:
  PHPMD:
    name: 运行 PHPMD 扫描
    runs-on: ubuntu-latest
    permissions:
      contents: read # 用于 checkout 获取代码
      security-events: write # 用于 github/codeql-action/upload-sarif 上传 SARIF 结果
      actions: read # 仅在私有存储库中由 github/codeql-action/upload-sarif 获取操作运行状态时需要

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 PHP
        uses: shivammathur/setup-php@aa1fe473f9c687b6fb896056d771232c0bc41161
        with:
          coverage: none
          tools: phpmd

      - name: 运行 PHPMD
        run: phpmd . sarif codesize --reportfile phpmd-results.sarif
        continue-on-error: true

      - name: 上传分析结果到 GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: phpmd-results.sarif
          wait-for-processing: true
