# 此工作流使用 GitHub 未认证的操作。
# 这些操作由第三方提供，并受独立的服务条款、隐私政策和支持文档约束。

name: Psalm Security Scan

on:
  push:
    branches: [ $default-branch, $protected-branches ]
  pull_request:
    # 下面的分支必须是上面分支的子集
    branches: [ $default-branch ]
  schedule:
    - cron: $cron-weekly

permissions:
  contents: read

jobs:
  php-security:
    runs-on: ubuntu-latest
    permissions:
      contents: read # 用于 actions/checkout 获取代码
      security-events: write # 用于 github/codeql-action/upload-sarif 上传 SARIF 结果
      actions: read # 仅在私有存储库中由 github/codeql-action/upload-sarif 获取操作运行状态时需要

    steps:
      - name: 代码检查
        uses: actions/checkout@v3

      - name: Psalm 安全扫描
        uses: psalm/psalm-github-security-scan@f3e6fd9432bc3e44aec078572677ce9d2ef9c287

      - name: 上传 GitHub 的安全分析结果
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
