# 此工作流使用 GitHub 未认证的操作。
# 这些操作由第三方提供，并受独立的服务条款、隐私政策和支持文档约束。

# 此工作流将 Pyre 与 GitHub 的
# Code Scanning 功能集成。
#
# Pyre 是一个符合 PEP 484 的 Python 高性能类型检查器。
# Pyre 可以增量地分析包含数百万行代码的代码库，
# 在开发人员编写代码时提供即时反馈。
#
# 详细信息请参阅 https://pyre-check.org

name: Pyre

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch, $protected-branches ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  pyre:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: 运行 Pyre
        uses: facebook/pyre-action@60697a7858f7cc8470d8cc494a3cf2ad6b06560d
        with:
          # 若要自定义这些输入：
          # 请参阅 https://github.com/facebook/pyre-action#inputs
          repo-directory: './'
          requirements-path: 'requirements.txt'
