# 此工作流使用 GitHub 未认证的操作。这些操作由第三方提供，并受独立的服务条款、隐私政策和支持文档约束。

name: trivy

on:
  push:
    branches: [ $default-branch, $protected-branches ]
  pull_request:
    # 下面的分支必须是上面分支的子集
    branches: [ $default-branch ]
  schedule:
    - cron: $cron-weekly

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # 用于 actions/checkout 获取代码
      security-events: write # 用于 github/codeql-action/upload-sarif 上传 SARIF 结果
      actions: read # 仅对私有存储库的 github/codeql-action/upload-sarif 需要，用于获取操作运行状态
    name: 构建
    runs-on: "ubuntu-20.04"
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 从 Dockerfile 构建镜像
        run: |
          docker build -t docker.io/my-organization/my-app:${{ github.sha }} .

      - name: 运行 Trivy 漏洞扫描器
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: 上传 Trivy 扫描结果到 GitHub 安全选项卡
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
