# 构建和部署 mdBook 站点到 GitHub Pages 的示例工作流
#
# 要开始使用 mdBook，请参阅: https://rust-lang.github.io/mdBook/index.html
#
name: 部署 mdBook 站点到 Pages

on:
  # 在推送到默认分支时运行
  push:
    branches: [$default-branch]

  # 允许您从“操作”选项卡手动运行此工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 仅允许一个并发部署，跳过在进行中的运行和最新排队运行之间的运行。
# 但是，不要取消进行中的运行，因为我们希望允许这些生产部署完成。
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 构建作业
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.21
    steps:
      - uses: actions/checkout@v3
      - name: 安装 mdBook
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
          rustup update
          cargo install --version ${MDBOOK_VERSION} mdbook
      - name: 设置 Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: 使用 mdBook 构建
        run: mdbook build
      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./book

  # 部署作业
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
