#这个工作流使用了GitHub未经认证的操作。
#这些操作是由第三方提供的，并受到独立的服务条款、隐私政策和支持文档的管理。

# 定义工作流的名称为D
name: D

# 控制工作流何时运行
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

# 设置权限，允许读取仓库内容
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7

    - name: 'Build & Test'
      run: |
        # 构建项目，包括其主文件，但不包括单元测试
        dub build --compiler=$DC
        # 构建和运行测试，由`unittest`配置定义
        # 在此模式下，`mainSourceFile`被排除，`version (unittest)` 被包含
        # 参见 https://dub.pm/package-format-json.html#configurations
        dub test --compiler=$DC
