# 此工作流使用未经GitHub认证的操作。
# 这些操作由第三方提供，并受独立的服务条款、隐私政策和支持文档约束。

# 此工作流使你能够使用符合SLSA3标准的构建器编译你的Go项目。
# 该工作流将生成一个所谓的“可信任性”文件，描述生成最终二进制文件的步骤。
# 该项目是OpenSSF（openssf.org）的一个倡议，并在 https://github.com/slsa-framework/slsa-github-generator 开发。
# 可以使用 https://github.com/slsa-framework/slsa-verifier 验证可信任性文件。
# 有关SLSA及其如何改善供应链的更多信息，请访问 slsa.dev。

name: SLSA Go发布器
on:
  workflow_dispatch:
  release:
    types: [created]

permissions: read-all

jobs:
  # ========================================================================================================================================
  # 先决条件：在项目的根目录中创建一个 .slsa-goreleaser.yml 文件。
  # 请参阅格式 https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/go/README.md#configuration-file
  #=========================================================================================================================================
  build:
    permissions:
      id-token: write # 用于签名。
      contents: write # 用于上传发布资产。
      actions: read   # 读取工作流路径。
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.4.0
    with:
      go-version: 1.17
      # =============================================================================================================
      # 可选：有关更多选项，请参阅 https://github.com/slsa-framework/slsa-github-generator#golang-projects
      # =============================================================================================================

