# 此工作流使用未经GitHub认证的操作。
# 这些操作由第三方提供，并受单独的服务条款、隐私政策和支持文档约束。
# 此工作流将使用Gradle构建软件包，然后在创建发布时将其发布到GitHub软件包。
# 了解更多信息: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: 设置JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # pom.xml文件中distributionManagement/repository/id字段的值
        settings-path: ${{ github.workspace }} # settings.xml文件的位置

    - name: 使用Gradle构建
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

    # USERNAME和TOKEN需要对应于build.gradle中发布部分使用的凭据环境变量
    - name: 发布到GitHub Packages
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
